// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ligato/vpp/wg/wg.proto

package vpp_wg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Device struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec30692b8834dbc, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Device) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Peer struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIp            string   `protobuf:"bytes,4,opt,name=allowed_ip,json=allowedIp,proto3" json:"allowed_ip,omitempty"`
	TunInterface         string   `protobuf:"bytes,5,opt,name=tun_interface,json=tunInterface,proto3" json:"tun_interface,omitempty"`
	PersistentKeepalive  uint32   `protobuf:"varint,6,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec30692b8834dbc, []int{1}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Peer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Peer) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Peer) GetAllowedIp() string {
	if m != nil {
		return m.AllowedIp
	}
	return ""
}

func (m *Peer) GetTunInterface() string {
	if m != nil {
		return m.TunInterface
	}
	return ""
}

func (m *Peer) GetPersistentKeepalive() uint32 {
	if m != nil {
		return m.PersistentKeepalive
	}
	return 0
}

func init() {
	proto.RegisterType((*Device)(nil), "ligato.vpp.wg.Device")
	proto.RegisterType((*Peer)(nil), "ligato.vpp.wg.Peer")
}

func init() { proto.RegisterFile("ligato/vpp/wg/wg.proto", fileDescriptor_9ec30692b8834dbc) }

var fileDescriptor_9ec30692b8834dbc = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0xad, 0xc5, 0x5e, 0x9d, 0x4d, 0x14, 0x09, 0x82, 0x58, 0xea, 0xa6, 0x1b, 0x27,
	0x48, 0xc5, 0x8d, 0xb8, 0x11, 0x37, 0xa5, 0x1b, 0xe9, 0xd2, 0xcd, 0x90, 0x4e, 0xaf, 0x21, 0x74,
	0x48, 0x2e, 0xe9, 0x9d, 0x0c, 0x7d, 0x47, 0x1f, 0x4a, 0xcc, 0x4c, 0xfd, 0x59, 0xb8, 0x4b, 0xbe,
	0x93, 0x73, 0x08, 0x1f, 0x5c, 0xd4, 0xd6, 0x68, 0xf6, 0x2a, 0x12, 0xa9, 0xd6, 0xa8, 0xd6, 0x14,
	0x14, 0x3c, 0x7b, 0x91, 0x77, 0xbc, 0x88, 0x44, 0x45, 0x6b, 0x26, 0x4f, 0x30, 0x7c, 0xc1, 0x68,
	0x2b, 0x14, 0xd7, 0x70, 0x42, 0xc1, 0x46, 0xcd, 0x58, 0x6e, 0x70, 0x27, 0xb3, 0x71, 0x36, 0x1d,
	0x2d, 0xa1, 0x47, 0x0b, 0xdc, 0x09, 0x01, 0x03, 0xf2, 0x81, 0xe5, 0xc1, 0x38, 0x9b, 0xe6, 0xcb,
	0x74, 0x9e, 0x7c, 0x64, 0x30, 0x78, 0x45, 0x0c, 0xe2, 0x0a, 0x80, 0x9a, 0x55, 0x6d, 0xab, 0x5f,
	0xe5, 0x51, 0x47, 0xfe, 0xe9, 0x8a, 0x4b, 0x38, 0x46, 0xb7, 0x26, 0x6f, 0x1d, 0xcb, 0xc3, 0x54,
	0xf8, 0xbe, 0x7f, 0xcd, 0xe9, 0xba, 0xf6, 0x2d, 0xae, 0x4b, 0x4b, 0x72, 0xd0, 0xcd, 0xf5, 0x64,
	0x4e, 0xe2, 0x06, 0x72, 0x6e, 0x5c, 0x69, 0x1d, 0x63, 0x78, 0xd7, 0x15, 0xca, 0xa3, 0xf4, 0xe2,
	0x94, 0x1b, 0x37, 0xdf, 0x33, 0x71, 0x07, 0xe7, 0x84, 0x61, 0x6b, 0xb7, 0x8c, 0x8e, 0xcb, 0x0d,
	0x22, 0xe9, 0xda, 0x46, 0x94, 0xc3, 0xf4, 0x87, 0xb3, 0x9f, 0x6c, 0xb1, 0x8f, 0x9e, 0x1f, 0xde,
	0xee, 0x8d, 0x2f, 0x7a, 0x43, 0x36, 0xc9, 0xbb, 0xd5, 0x06, 0x1d, 0xab, 0x38, 0x53, 0xc9, 0x9f,
	0xfa, 0xa3, 0xf5, 0x31, 0x12, 0x95, 0xad, 0x59, 0x0d, 0x53, 0x36, 0xfb, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x58, 0x83, 0x15, 0x75, 0x01, 0x00, 0x00,
}
